config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  get 'airlock/index'

  resources :posts do
    resources :comments, shallow: true
  end

  root 'airlock#index'






  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :post
end

app/models/post.rb
class Post < ApplicationRecord

  belongs_to :user, optional: true
  has_many :comments, dependent: :destroy
  validates :content, presence: true, length: { maximum: 300 }
  validates :content, length: { maximum: 50 }, if: -> { user_id.nil? }

end

app/models/user.rb
class User < ApplicationRecord

  has_many :posts, dependent: :destroy
  has_many :comments, dependent: :destroy

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/airlock_controller.rb
class AirlockController < ApplicationController
  def index
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:username])
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

  def index
    get_post
    @comments = @post.comments.all
  end

  def new
    get_post
    @comment = @post.comments.new
  end

  def create
    get_post
    @comment = @post.comments.build(comment_params)
    @comment.save
    redirect_to post_comments_path(@post)
  end

  def destroy
    @comment = Comment.find(params[:id])
    @comment.destroy
    redirect_to post_comments_path(@comment.post)
  end
  private

  def get_post
    @post = Post.find(params[:post_id])
  end

  def comment_params
    params.require(:comment).permit(:message, :user_id, :post_id)
  end

end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  def new
    @post = Post.new
  end

  def create
    @post = posting_as_user?
    @post.save
    redirect_to posts_path
  end

  def destroy
    @post = Post.find(params[:id])
    @post.destroy
    redirect_to posts_path
  end

  def index
    @posts = Post.all
  end

  private

  def post_params
    params.require(:post).permit(:content, :user_id)
  end

  def posting_as_user?
    current_user ? current_user.posts.new(post_params) : Post.new(post_params)
  end

end

app/helpers/airlock_helper.rb
module AirlockHelper
end

app/helpers/application_helper.rb
module ApplicationHelper

  def date(date)
    return "#{date.day}|#{date.month}|#{date.year}"
  end

  def time(time)
    output = "#{time.hour}:"
    output += "0" if time.min < 10
    output += "#{time.min}"
    return output
  end

  def author_of(content)
    return content.user ? content.user.username : 'n/a'
  end
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/airlock/index.html.erb
<body>
  <h2>Welcome aboard, visitor</h2>

</body>

app/views/comments/index.html.erb
<div id="original_post">
  <%= date(@post.created_at) %>; <%= time(@post.created_at) %><br>
  <%= @post.content %>
  <div id="post_footer">
  Entered by: <%= author_of(@post)%>
  <%- if current_user %>
  || <%= link_to 'Generate Comment', new_post_comment_path(@post), method: :get %>
  <% end %>
  </div>
</div>

<br>
<% @comments.reverse.each do |comment| %>
  <div class="comment_body" id="<%= comment.id %>">
    <%= date(comment.created_at)%>; <%= time(comment.created_at) %><br>
    <%= comment.message %>
    <div class="comment_footer">
      Entered by: <%= author_of(comment) %>
      <%- if current_user && comment.user_id == current_user.id %>
      || <%= link_to 'Erase Comment', comment_path(comment), method: :delete %>
      <% end %>
    </div>
  </div>
<% end %>

app/views/comments/new.html.erb
<%= form_with model: [@post, @post.comments.build] do |form| %>
  <%= form.label(:message, "Message to be entered:") %><br><br>
  <%= form.hidden_field :user_id, value: current_user.id %>
  <%= form.text_area :message %> <br>
  <%= form.submit "Enter Comment"%>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Explorum</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div id="Header_bar">
      <h1>_EXPLORUM_</h1><br>
      <%= link_to "View Logs", posts_path, method: :get %> ||
      <%= link_to "Generate Log", new_post_path, method: :get %> ||
      <%= link_to "Sign on", new_user_session_path, method: :get unless user_signed_in? %>
      <%= link_to "Sign off", destroy_user_session_path, method: :delete if user_signed_in? %>
      <br><br>
      <%= "Using as: #{current_user.username}" if user_signed_in? %>
      </div>

    <%= yield %>
  </body>
</html>

app/views/posts/index.html.erb
<% @posts.reverse.each do |post| %>
  <div class="post_body" id="<%= post.id %>">
    <%= date(post.created_at) %>; <%= time(post.created_at) %><br>
    <%= post.content %><br><br>
    Entered by: <%= author_of(post) %>
    <%- if current_user && post.user_id == current_user.id %>
      || <%= link_to 'Erase Log', post_path(post), method: :delete %>
    <% end %>
    || <%= link_to 'View Comments', post_comments_path(post), method: :get %>
  </div>
<% end %>

app/views/posts/new.html.erb
<%= form_with model: @post do |form| %>
  <%= form.label(:content, "Content to be entered:") %><br><br>
  <%= form.text_area :content%> <br>
  <%= form.submit "Enter Log"%>
<% end %>

app/views/users/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation">
    <h3>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h3>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/users/shared/_links.html.erb
<br>
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %>
<% end %>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %>
<% end %>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %>
<% end %>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %>
<% end %>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %>
<% end %>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider) %>
  <% end %>
<% end %>